services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: mybizna
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "your_root_password"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - laravel_network      
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - laravel_network     

volumes:
  mariadb_data:


networks:
  laravel_network:
    driver: bridge

